/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package genioadvinhacao;

import java.awt.Font;
import java.util.Random;

/**
 *
 * @author berit
 */
public class TelaGenio extends javax.swing.JFrame {

    /**
     * Creates new form TelaGenio
     */
    public TelaGenio() {
        initComponents();
        lblBalaoFala.setText("<html>Tente advinhar em que número estou pensando!<br><br>Escolha um numero de <strong>0 a 5</strong>!</html>");
        imgGenioPensando.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNum = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        imgGenioFalando = new javax.swing.JLabel();
        btnTentar = new javax.swing.JButton();
        imgGenioPensando = new javax.swing.JLabel();
        lblBalaoFala = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNum.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        getContentPane().add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 340, 70, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Valor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        imgGenioFalando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/geniofalando.png"))); // NOI18N
        getContentPane().add(imgGenioFalando, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        btnTentar.setBackground(new java.awt.Color(51, 117, 253));
        btnTentar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTentar.setText("TENTAR");
        btnTentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTentarActionPerformed(evt);
            }
        });
        getContentPane().add(btnTentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 190, 50));

        imgGenioPensando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/geniopensando.png"))); // NOI18N
        getContentPane().add(imgGenioPensando, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        lblBalaoFala.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBalaoFala.setForeground(new java.awt.Color(0, 124, 203));
        lblBalaoFala.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBalaoFala.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblBalaoFala, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 210, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/balaofala.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTentarActionPerformed
        
        imgGenioFalando.setVisible(false);
        imgGenioPensando.setVisible(true);
        
              
        int usuario = (int) txtNum.getValue();
        Random rand  = new Random();
        int genioEscolha = rand.nextInt(6);
        
        String res = (usuario == genioEscolha)? String.format("<html><br><strong>ACERTOU</strong><br><br>pensei em %d também</html>",genioEscolha) : String.format("<html><br><strong>ERROU</strong><br><br>pensei em %d, tente novamente</html>",genioEscolha);
        
        lblBalaoFala.setFont(new Font("Arial Black", Font.PLAIN,16));
        lblBalaoFala.setText(res);
    }//GEN-LAST:event_btnTentarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGenio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTentar;
    private javax.swing.JLabel imgGenioFalando;
    private javax.swing.JLabel imgGenioPensando;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblBalaoFala;
    private javax.swing.JSpinner txtNum;
    // End of variables declaration//GEN-END:variables
}
